---

- hosts: all

  tasks:
    - name: list the IPs of the instances
      ec2_remote_facts:
        region: us-west-2
        filters:
          instance-state-name: running
          "tag:Name": qa_win7_vms
      register: ec2_info

    - name: Get only running instance IP addresses.
      debug:
        msg: "Instance: {{ item.0 }} has IP address: {{ item.1 }}"
      with_together:
        - "{{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
        - "{{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_ip_address')|list }}"

    - name: send email to the users
      local_action: mail
                    host='smtp.gmail.com'
                    port=465
                    username=testaws1005@gmail.com
                    password='testAWS1005$'
                    to="Gopi Desam <testAWS1005@gmail.com>"
                    subject='Ansible-report'
                    body='Public IPs of the running instances are {{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_ip_address')|list }}'
