---

- hosts: all
  vars:
    region: us-west-2

  tasks:
    - name: list the IPs of the instances
      ec2_remote_facts:
        region: us-west-2
        filters:
          instance-state-name: running
          "tag:Name": qa_win7_vms
      register: ec2_info

    - name: terminate the running ec2 instances
      ec2:
        region: us-west-2
        state: absent
        instance_ids: '{{ item }}'
      with_items:
        - "{{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"
