---

- hosts: all
  vars:
    keypair: desam
    instance_type: t2.micro
    security_group: default
    image: ami-4d63df2d
    region: us-west-2

  tasks:
#    - name: list the instances created using ami-4d63df2d
#      shell: aws ec2 describe-instances --filters "Name=image-id,Values=ami-4d63df2d"

    - name: Create Windows7 EC2 instances
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        count: "{{ count }}"
        region: "{{ region }}"
        instance_tags:
            Name: qa_win7_vms
        wait: true
      register: ec2
#      shell: aws ec2 run-instances --image-id ami-4d63df2d --count {{count}} --instance-type t2.micro --key-name desam --security-groups default

    - name: pause for 5 mins for the instances to come up
      local_action: pause minutes=4

    - name: list the IPs of the instances
      ec2_remote_facts:
        region: us-west-2
        filters:
          instance-state-name: running
          "tag:Name": qa_win7_vms
      register: ec2_info

    - name: Get only running instance IP addresses.
      debug:
        msg: "Instance: {{ item.0 }} has IP address: {{ item.1 }}"
      with_together:
        - "{{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
        - "{{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_ip_address')|list }}"

#    - name: list the IPs of the instances
#      shell: /usr/local/bin/aws ec2 describe-instances --query 'Reservations[].Instances[].[PublicDnsName]' --output table | sed '$!N;s/\n/ /'

    - name: send email to the users
      local_action: mail
                    host='smtp.gmail.com'
                    port=465
                    username=testaws1005@gmail.com
                    password='testAWS1005$'
                    to="Gopi Desam <testAWS1005@gmail.com>"
                    subject='Ansible-report'
                    body='Public IPs of the running instances are {{ ec2_info.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_ip_address')|list }}'
